// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Character struct {
	ID       string    `json:"id"`
	Name     string    `json:"name"`
	Status   *string   `json:"status,omitempty"`
	Species  *string   `json:"species,omitempty"`
	Type     *string   `json:"type,omitempty"`
	Gender   *string   `json:"gender,omitempty"`
	Origin   *Location `json:"origin,omitempty"`
	Location *Location `json:"location,omitempty"`
	Image    *string   `json:"image,omitempty"`
}

type Episode struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Location struct {
	ID   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

type RickAndMortyAssociation struct {
	Rick    *Character   `json:"rick"`
	Morties []*Character `json:"morties"`
}
